/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* biome-ignore-all lint: auto-generated */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_MEDIMADE_API_URL: string
  readonly VITE_MARKETING_ORIGIN: string
  readonly VITE_MEDIMADE_MEDIA_BASE_URL: string
  readonly VITE_MEDIMADE_CHAT_URL: string
  readonly VITE_ASSISTANT_CHAT_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}