/** Re-export shared color scheme — do not edit here; change `@consciously/common`. */
export {
  type ColorScheme,
  COLOR_SCHEME_STORAGE_KEY,
  COLOR_SCHEME_CHANGED_EVENT,
  COLOR_SCHEME_QUERY_PARAM,
  COLOR_SCHEME_OPTIONS,
  HOME_HERO_PATTERN_LIGHT,
  HOME_HERO_PATTERN_DARK,
  AUTH_HERO_PATTERN_LIGHT,
  AUTH_HERO_PATTERN_DARK,
  getStoredColorScheme,
  parseColorScheme,
  getLiveColorScheme,
  isDarkColorScheme,
  resolveAuthColorScheme,
  withAuthColorSchemeQuery,
  applyColorScheme,
  setColorScheme,
  toggleColorScheme,
  colorSchemeBootScript,
} from "@consciously/common/theme";
